name: on-push

env:
  BUILD_ARGS: '--test'

on:
  push:
    branches:
      - main
  pull_request_target:
    types: [opened, synchronize, reopened, review_requested]
    branches:
      - main

jobs:
  build_addon:
    name: Build ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: ['aarch64', 'amd64', 'armhf', 'armv7', 'i386']

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Get information
        id: info
        uses: home-assistant/actions/helpers/info@master
        with:
          path: './addon'

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build add-on
        uses: home-assistant/builder@master
        with:
          args: |
            ${{ env.BUILD_ARGS }} \
            --${{ matrix.arch }} \
            --target /data/addon \
            --docker-hub homeassistant
